<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

/**
 * @category   Innovadeltech
 * @package    Innovadeltech_Wishlist
 * @subpackage view
 * @author     Ijaz Ali <info@innovadeltech.com>
 * @copyright  Copyright (c) 2018 Innovadeltech Technologies (http://www.innovadeltech.com)
 * @version    ${release.version}
 * @link       http://www.innovadeltech.com/
 */

/**
 * @var $this \Innovadeltech\Wishlist\Block\Adminhtml\Management\Edit
 */
?>
<?php
/** @var $helper Innovadeltech\Wishlist\Helper\Data */
$helper = $this->helper('Innovadeltech\Wishlist\Helper\Data');
?>
<div id="container">
    <div class="row">
        <div class="col-m-4">
            <?php if ($customer = $this->getCustomer()): ?>
                <h3><?php echo _('Customer information') ?></h3>
                <span><b><?php echo _('Name:') ?> </b></span><span><?php echo $customer->getName() ?> (<a href="<?php echo $helper->getCustomerEditLink($customer->getId()) ?>" target="_blank"><?php echo _('View customer') ?></a>)</span>
                <br>
                <span><b><?php echo _('Email:') ?> </b></span><span><a href="mailto:<?php echo $customer->getEmail() ?>" target="_top"><?php echo $customer->getEmail() ?></a></span>

                <br><br>
                <h3><?php echo _('Default billing address') ?></h3>
                <?php echo $this->getBillingAddressHtml() ?>
            <?php endif; ?>
        </div>
        <div class="col-m-4">
            <?php if ($product = $this->getProduct()): ?>
                <?php $itemId = $product->getId();?>
                <?php $helper->register('product', $product); ?>
                <h3><?php echo _('Wishlist Item') ?></h3>
                <?php if (!$product->getId()): ?>
                    <div class="notification-message message message-warning"><?php echo __('The product is no longer available') ?></div>
                <?php else: ?>
                    <a href="<?php echo $helper->getProductEditLink($product->getId()) ?>" target="_blank">
                        <img src="<?php echo $helper->getProductImageSrc($product) ?>">
                    </a>
                    <br>
                    <span><?php echo $product->getName(); ?></span>
                    <br>
                    <span><b>SKU: </b></span><span><?php echo $product->getSku() ?></span>
                    <br>
                    <span style="width:11%; float:left;"><b>Price: </b></span><span style="width:70%;"><?php echo $this->getChildHtml('product.price.final') ?></span>
                    <span><b>Qty: </b></span><span><?php echo $this->getQty();?></span>
                    <br>
                    <span><b>Added at: </b></span><span><?php echo $helper->getCreatedAt($product->getId(),$customer->getId()); ?></span>
                    <br>
                    <span><a href="<?php echo $helper->getProductEditLink($product->getId()) ?>" target="_blank">Edit</a></span>
                    
                <?php endif; ?>
                
                
                
                <br>
                
            <?php endif; ?>
        </div>
        <div class="col-m-4 "> 
            <h3><?php echo _('Notification status') ?></h3>
            <div class="switcher" onselectstart='return false;'>
                <input type="checkbox" id="status-switcher" name="status-switcher" />
                <label class="switcher-label"
                       for="status-switcher"
                       data-text-on="<?php echo __('Checked'); ?>"
                       data-text-off="<?php echo __('Unchecked'); ?>"
                       title="<?php echo __('Mark as checked'); ?>"></label>
            </div>
            
            <div class="forButton">
                <a href="<?php echo $helper->getCustomerNotifyLink($itemId);?>">Notify Now</a>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-m-12 wishlist">
            <?php if ($wishlist = $this->getWishlist()): ?>
            <?php 
//                echo '<pre>'; 
//                print_r($customer->getData());
//                echo '</pre>'; 
            ?>
            
                <h3><?php echo $customer->getData('firstname'). _("'s current wishlist") ?></h3>
                <?php /** @var $item Magento\Wishlist\Model\Item */ ?>
                <?php
                $abstractProductBlock = $block->getLayout()->createBlock('\Magento\Catalog\Block\Product\AbstractProduct');
                ?>
                <?php foreach($wishlist->getItemCollection() as $item): ?>
                    <?php $product = $item->getProduct() ?>
                    <?php $helper->register('product', $product); ?>
                    <div class="wishlist-item">
                        <a href="<?php echo $helper->getProductEditLink($product->getId()) ?>" target="_blank">
                            <img src="<?php echo $helper->getProductImageSrc($product) ?>">
                        </a>
                        <br>
                        <span><?php echo $product->getName() ?></span>
                        <br>
                        <span><b>SKU: </b></span><span><?php echo $product->getSku() ?></span>
                        <br>
                        <span style="width:21%; float:left;"><b>Price: </b></span><span style="width:70%;"><?php echo $abstractProductBlock->getProductPrice($product) ?></span>
                        <span><b>Qty: </b></span><span><?php echo $helper->getProductQty($product->getId());?></span>
                        <br>
                        <span><b>Added at: </b></span><span><?php echo $helper->getCreatedAt($product->getId(),$customer->getId()); ?></span>
                        <br>
                        <span><a href="<?php echo $helper->getProductEditLink($product->getId()) ?>" target="_blank">Edit</a></span>
                        <br>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>
</div>

<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="edit-notification" enctype="multipart/form-data" data-form="edit-notification">
    <?php echo $this->getBlockHtml('formkey')?>
    <input id="status" name="notification[status]" value="<?php echo $this->getStatus() ?>" class="" type="hidden">
    <button type="submit" class="hidden"></button>
</form>

<script>
require([
    "jquery",
    "Magento_Catalog/catalog/type-events",
    "underscore",
    "mage/mage",
    "domReady!"
], function($, TypeSwitcher){
    var $form = $('[data-form=edit-notification]');
    $form.data('typeSwitcher', TypeSwitcher.init());

    $form.mage('form', {
        handlersData: {
            save: {}
        }
    });

    $('#status-switcher')
        .prop('checked', $('#status').val() == '1')
        .trigger('change');

    $('#status-switcher').on('change', function(event) {
        $('#status').val($(this).prop('checked') ? '1' : '0');
    });
});
</script>